version: '3'
services:
  db:
    image: postgres:14
    container_name: postgresql_app
    restart: always
    expose:
      - 5432
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_NAME}

  redis:
    image: redis:7
    container_name: redis_app
    command: --port 6379
    expose:
      - 6379

  django:
    build:
      context: ./noncountries/
    command: ["/usr/src/app/docker/app.sh"]
    volumes:
      - ./noncountries/:/usr/src/app
#      - static_files:/usr/src/app/staticfiles
    expose:
      - 8000
    env_file:
      - ./.env
    depends_on:
      - db
      - redis





