# Generated by Django 4.0.8 on 2023-02-09 11:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255, verbose_name='Категория')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Язык')),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('original_name', models.CharField(max_length=255, verbose_name='Оригинальное название')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
                ('area', models.IntegerField(verbose_name='Площадь')),
                ('population', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Население')),
                ('year', models.IntegerField(verbose_name='Год основания')),
                ('description', models.TextField(null=True, verbose_name='Описание')),
                ('reasons', models.TextField(blank=True, verbose_name='Причины')),
                ('flag', models.ImageField(upload_to='countries/flags/', verbose_name='Флаг')),
                ('emblem', models.ImageField(upload_to='countries/emblems/', verbose_name='Герб')),
                ('map', models.ImageField(upload_to='countries/maps/', verbose_name='Карта')),
                ('anthem', models.FileField(null=True, upload_to='countries/anthems/', verbose_name='Гимн')),
                ('capital', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='countries.city', verbose_name='Столица')),
                ('cat', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='countries.category', verbose_name='Категория')),
                ('language', models.ManyToManyField(to='countries.language', verbose_name='Язык')),
            ],
        ),
    ]
